# Out-dated 

version: "3"

services: 
  flask:
    build: ./server
    hostname: server
    ports:
      - "5001:5000"
    volumes: 
      - ./server:/usr/src/app
    container_name: server
    restart: unless-stopped

    depends_on: 
      - mongo
    
  mongo:
    image: mongo
    hostname: mongo # pass to mongoclient
    volumes: 
      - ./database:/data
    container_name: database
    ports:
      - "2717:27017"
    restart: unless-stopped
  
  vue:
    build: ./client
    volumes: 
      - ./client:/app
    container_name: client
    ports: 
      - "8081:8080"
    depends_on: 
      - flask
