# version: '3.1'  # the syntax version
# services: # the containers

#     app:  # web server 
#         build: . # build the Dockerfile image
#         ports: 
#             - "5000:5000" # host port : container port
#         volumes:
#             - .:/app # store the data in container/app outside, at host/.
#         links: 
#             - mongo

            
#     mongo:
#         image: mongo
#         restart: on-failure

version: "3.7"


services:
# first container
    backend:
        # look for dockerfile and build the container
        build: ./backend
        container_name:  backend
        restart: always
        # set enviornemt variables
        environment: 
            - APP_NAME=FlaskApp
        #  mount the volumes so we can change code and hot reload
        volumes:
            - './backend:/backend'
        #  expose port on the container, only to other containers
        expose:
            - 8080
        links: 
            - mongo

    nginx:
        build: ./nginx
        container_name:  nginx
        restart: always
        # port allows the host machine to link to container
        # pass 80 from host machine to 80 of the image filesystem
        ports:
            - "8082:8082"

    frontend:
        build: ./frontend
        container_name:  frontend
        restart: always
        #  mount the volumes so we can change code and hot reload
        volumes:
            - './frontend:/frontend'

        #  port allows the host machine to link to container
        #  8000 for vue ui, 5000 for our vue app
        ports:
            - "8000:8000"
            - "5000:5000"

    # mongodb:
    #     image: mongo:4.2.5-bionic
    #     container_name:  mongodb
    #     restart: always
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=root
    #         - MONGO_INITDB_ROOT_PASSWORD=example
    #     volumes:
    #         - './database:/data/db'
    #     ports:
    #         - "27017:27017"
    #         - "27018:27018"
    #         - "27019:27019"
    #     expose:
    #         - 27017
    #         - 27018
    #         - 27019

    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     environment:
    #         # mongodb authentication
    #         - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    #         - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    #         # mongodb URI
    #         - ME_CONFIG_MONGODB_SERVER=mongodb
    #         - ME_CONFIG_MONGODB_PORT=27017
    #         # web login username and password
    #         - ME_CONFIG_BASICAUTH_USERNAME=mongo
    #         - ME_CONFIG_BASICAUTH_PASSWORD=express
    #     ports:
    #         - 8081:8081
    mongo:
        image: mongo
        restart: on-failure