apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    service: {{ .Values.mongo.name }}
spec:
  selector:
    service: {{ .Values.mongo.name }}
  type: {{ .Values.mongo.serviceType }}
  ports:
  - port: {{ .Values.mongo.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
  labels:
    service: {{ .Values.flask.name }}
spec:
  selector:
    app: {{ .Values.flask.name }}
  ports:
  - port: {{ .Values.flask.port }}
    targetPort: {{ .Values.flask.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vue.name }}
  labels:
    service: {{ .Values.vue.name }}
spec:
  selector:
    app: {{ .Values.vue.name }}
  ports:
  - port: {{ .Values.vue.port }}
    targetPort: {{ .Values.vue.targetPort }}